const testingCentres = [
  {
    id: 0,
    gov_name_tc: "東區鰂魚涌社區會堂",
    gulu_code: "",
    region: "港島",
    district: "東區",
  },
  {
    id: 1,
    gov_name_tc: "灣仔禮頓山社區會堂",
    gulu_code: "",
    region: "港島",
    district: "灣仔區",
  },
  {
    id: 2,
    gov_name_tc: "中西區石塘咀體育館",
    gulu_code: "400052",
    region: "港島",
    district: "中西區",
  },
  {
    id: 3,
    gov_name_tc: "南區利東社區會堂",
    gulu_code: "400067",
    region: "港島",
    district: "南區",
  },
  {
    id: 4,
    gov_name_tc: "梁顯利油麻地社區中心",
    gulu_code: "400064",
    region: "九龍",
    district: "油尖旺區",
  },
  {
    id: 5,
    gov_name_tc: "油塘社區會堂",
    gulu_code: "",
    region: "九龍",
    district: "觀塘區",
  },
  {
    id: 6,
    gov_name_tc: "深水埗白田社區會堂 (白雲街白田社區綜合大樓地下)",
    gulu_code: "",
    region: "九龍",
    district: "深水埗區",
  },
  {
    id: 7,
    gov_name_tc: "黃大仙東頭社區中心",
    gulu_code: "400066",
    region: "九龍",
    district: "黃大仙區",
  },
  {
    id: 8,
    gov_name_tc: "九龍城土瓜灣體育館",
    gulu_code: "400053",
    region: "九龍",
    district: "九龍城區",
  },
  {
    id: 9,
    gov_name_tc: "觀塘牛頭角道體育館",
    gulu_code: "",
    region: "九龍",
    district: "觀塘區",
  },
  {
    id: 10,
    gov_name_tc: "沙田瀝源社區會堂",
    gulu_code: "",
    region: "新界",
    district: "沙田區",
  },
  {
    id: 11,
    gov_name_tc: "元朗市東社區會堂",
    gulu_code: "",
    region: "新界",
    district: "元朗區",
  },
  {
    id: 12,
    gov_name_tc: "屯門兆麟社區會堂",
    gulu_code: "",
    region: "新界",
    district: "屯門區",
  },
  {
    id: 13,
    gov_name_tc: "粉嶺和興社區會堂",
    gulu_code: "",
    region: "新界",
    district: "北區",
  },
  {
    id: 14,
    gov_name_tc: "荔景社區會堂",
    gulu_code: "",
    region: "九龍",
    district: "葵青區",
  },
  {
    id: 15,
    gov_name_tc: "坑口社區會堂",
    gulu_code: "",
    region: "新界",
    district: "西貢區",
  },
  {
    id: 16,
    gov_name_tc: "荃灣蕙荃體育館",
    gulu_code: "400042",
    region: "新界",
    district: "荃灣區",
  },
  {
    id: 17,
    gov_name_tc: "大埔太和體育館",
    gulu_code: "",
    region: "新界",
    district: "大埔區",
  },
  {
    id: 18,
    gov_name_tc: "香港國際機場地面運輸候車室(1號停車場及機場巴士站旁)",
    gulu_code: "",
    region: "新界",
    district: "離島區",
  },
  {
    id: 19,
    gov_name_tc: "黃大仙廣場流動採樣站",
    gulu_code: "400061",
    region: "九龍",
    district: "黃大仙區",
  },
  {
    id: 20,
    gov_name_tc: "睦鄰街遊樂場流動採樣站",
    gulu_code: "400062",
    region: "九龍",
    district: "黃大仙區",
  },
  {
    id: 21,
    gov_name_tc: "慈雲山社區會堂流動採樣站",
    gulu_code: "400055",
    region: "九龍",
    district: "黃大仙區",
  },
  {
    id: 22,
    gov_name_tc: "麗閣社區會堂流動採樣站",
    gulu_code: "400051",
    region: "九龍",
    district: "深水埗區",
  },
  {
    id: 23,
    gov_name_tc: "長沙灣體育館流動採樣站",
    gulu_code: "400044",
    region: "九龍",
    district: "深水埗區",
  },
  {
    id: 24,
    gov_name_tc: "東涌北公園流動採樣站",
    gulu_code: "400065",
    region: "新界",
    district: "離島區",
  },
  {
    id: 25,
    gov_name_tc: "馬鞍山遊樂場流動採樣站",
    gulu_code: "400060",
    region: "新界",
    district: "沙田區",
  },
  {
    id: 26,
    gov_name_tc: "馬鞍山遊樂場流動採樣站",
    gulu_code: "400054",
    region: "新界",
    district: "沙田區",
  },
  {
    id: 27,
    gov_name_tc: "大窩口社區中心流動採樣站",
    gulu_code: "400050",
    region: "新界",
    district: "荃灣區",
  },
  {
    id: 28,
    gov_name_tc: "安定／友愛社區中心流動採樣站",
    gulu_code: "400049",
    region: "新界",
    district: "屯門區",
  },
  {
    id: 29,
    gov_name_tc: "天瑞體育館流動採樣站",
    gulu_code: "40048",
    region: "新界",
    district: "元朗區",
  },
  {
    id: 30,
    gov_name_tc: "荃灣公園流動採樣站",
    gulu_code: "400040",
    region: "新界",
    district: "荃灣區",
  },
  {
    id: 31,
    gov_name_tc: "葵涌運動場流動採樣站",
    gulu_code: "400041",
    region: "新界",
    district: "葵青區",
  }
];

module.exports = {
  testingCentres
}
